### PR TITLE
feat: Add option to install updater

### PR DESCRIPTION
**Pull request by spencergilbert**

### CODE REVIEW

**Review by raphaelgavache — APPROVED** [review]
thank's a lot!

**Comment by spencergilbert** [comment]
Rebased on `main` post 1.28.2 release, I expect e2e tests to fail on ubuntu for the updater still.

**Comment by spencergilbert** [comment]
@raphaelgavache can you double check the most recent commit? Shellcheck hadn't run on your PR (I assume "external PR" or something similar), and it had me look at this. I think your original addition was missing the `dd_` prefix but I wanted to double check.

**Comment by raphaelgavache** [comment]
Yes, thanks for fixing it!

**Review by chouquette — APPROVED** [review]

**Pull request merged**
