### PR TITLE
[e2e] part 3: extract one test per mode

### PR DESCRIPTION
**Pull request by pducolin**
Remove need for mode flag

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Duplicating a bunch of the test is a bit of a bummer, but clear upgrade on the `else if` statement.

**Comment by pducolin** [comment]
Do not ask why git found conflicts when there were not 🤷‍♀️ , maybe different commit hash

**Comment by pducolin** [comment]
Passing e2e test: https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/352128838

**Pull request merged**
